### PR TITLE
Feat: Update result_link and report_link

### PR DESCRIPTION
**Pull request by SHA888**
### JIRA Link

https://blocksphere2020.atlassian.net/browse/DBIO-344?atlOrigin=eyJpIjoiMDYxZjA0NzQ0YTc1NGY5MmI0OWNjYzMwYzk1MDA5YzkiLCJwIjoiaiJ9

### Changelog / Description
substrate | Update extrinsic submit dna sampe result_link dan report_link jadi required
- add report_link become required

### BREAKING CHANGE:
- No breaking change

### CODE REVIEW

**Comment by agustinustheo** [comment]
Don't comment code, just delete them, we are using Git so if we want to revert we can look at the history, I think it would be better to reserve comments for code documentation purposes.

**Comment by SHA888** [comment]
@agustinustheo Oh I see. My bad, sometimes I forgot to delete them. Thank you mas for the corrections

**Comment by SHA888** [comment]
@agustinustheo Comments deleted

**Review by kevinjanada — APPROVED** [review]

**Comment by kevinjanada** [comment]
> ### JIRA Link
> https://blocksphere2020.atlassian.net/browse/DBIO-344?atlOrigin=eyJpIjoiMDYxZjA0NzQ0YTc1NGY5MmI0OWNjYzMwYzk1MDA5YzkiLCJwIjoiaiJ9
> 
> ### Changelog / Description
> substrate | Update extrinsic submit dna sampe result_link dan report_link jadi required
> 
> * add report_link become required
> 
> ### BREAKING CHANGE:
> * No breaking change

btw bli @SHA888 , kalo no breaking change footer BREAKING CHANGE nya di ilangin aja gpp hehe

**Pull request merged**
